### ISSUE TITLE
Auto-deploy docker containers to dockerhub

### ISSUE THREAD

**Issue by ghost** [cltk/cltk_docker#5]
Corresponding thread: <a href="https://github.com/cltk/cltk_docker/pull/3#issuecomment-198072854">issuecomment-198072854</a>

**Comment by kylepjohnson** [comment]
For this issue, I'd like you to look at how some NLTK containers are built, such as this one here: https://hub.docker.com/r/trackmaven/nltk/

I'm interested in a few things:
- Can you add a "Source Repository" field, as in the above?
- Add Usage in the "Full Description"
- See how you can get the [Dockerfile in it, as above](https://hub.docker.com/r/trackmaven/nltk/~/dockerfile/).
- Look into [the Webhook option](https://hub.docker.com/r/cltk/cltk/~/settings/webhooks/). This is how we might be able to pull the latest version automatically

**Comment by ghost** [comment]
Thanks for the resources, I will start working on this.

**Comment by ghost** [comment]
Hello sir, 
- I have figured out on how to build container and pushed it to my docker hub repo : https://hub.docker.com/r/achaitanyasai/cltk_docker/
- And now coming to your requests:
  - [x] Can you add a "Source Repository" field, as in the above ?
  - [x] Add Usage in the "Full Description"
  - [x] See how you can get the Dockerfile in it, as above.
  - [ ] Look into the Webhook option. This is how we might be able to pull the latest version automatically.
  - I will find out and complete the pending task(last task) soon.
- And It seems like I don't have access to https://hub.docker.com/r/cltk/cltk/ can you please look into it. My username is  <code>achaitanyasai</code>.
- Also the [container size is 3GB](https://hub.docker.com/r/achaitanyasai/cltk/tags/) (because of corpora), isn't it too large ? If yes, we can just download only required / frequently used corpora instead of downloading all the corpora at once.

**Comment by kylepjohnson** [comment]
Hi, Yes, that's probably too large. However when we serve on the web, we'll want to pull down everything. Can you think of a way to make the downloads optional? Or maybe allow users to download everything for 1 language?

**Comment by kylepjohnson** [comment]
> And It seems like I don't have access to https://hub.docker.com/r/cltk/cltk/ can you please look into it. My username is achaitanyasai.

I have re-added you as an admin and confirmed you have write access. Try again and let me know if I did it right.

**Comment by ghost** [comment]
<blockquote>
Can you think of a way to make the downloads optional? Or maybe allow users to download everything for 1 language?
</blockquote>

I think first idea is OK but instead of making downloads optional, downloading the mostly used corpora is better. "mostly used corpora" in the sense the corpora that get's downloaded into <code>~/cltk_data</code> by default. 
And if we allow users to download everything for one language, it's more beneficial to the user who works only on one particular language. But we end up making containers for each language. So I feel it's a bad idea. What about your opinion ?

<blockquote>
I have re-added you as an admin and confirmed you have write access. Try again and let me know if I did it right.
</blockquote>

Thanks, now it's OK. I will deploy the container into <code>cltk/cltk</code> very soon.

**Comment by kylepjohnson** [comment]
@achaitanyasai I'm finally getting back to this.

> I think first idea is OK but instead of making downloads optional, downloading the mostly used corpora is better. "mostly used corpora" in the sense the corpora that get's downloaded into ~/cltk_data by default. 

There will be so many different users of the CLTK that there no "most used". In a few months, I'll have an idea about which corpora we'll serve with API. At that point I'd like to slim down the repos to just those.

 Are we ready to close this now? Anything else you want to take care of?

**Comment by ghost** [comment]
Yeah, it's a very nice idea of serving corpora through API.

No, we can close this issue.

**Comment by kylepjohnson** [comment]
I'll reach out when we know more about the website and api.

Are you interested in starting on preliminary repos for cltk_api (Python/Flask) and cltk_frontend (JavaScript/Meteor)?

**Comment by ghost** [comment]
Yes I am interested in starting on preliminary repos.
